boostpad-block: "GLOWSTONE"
boostpad-plate: "HEAVY_WEIGHTED_PRESSURE_PLATE"
boostpad-add-height-multiplier: 1.0
boostpad-add-velocity-multiplier: 2.0

djump-add-height-multiplier: 0.75
djump-add-velocity-multiplier: 1.5