#LOBBY
lobby-world: "world"

#LOBBY BOOSTPAD
boostpad-block: "GLOWSTONE"
boostpad-plate: "HEAVY_WEIGHTED_PRESSURE_PLATE"
boostpad-add-height-multiplier: 0.6
boostpad-add-velocity-multiplier: 2.5

#LOBBY DOUBLEJUMP
djump-add-height-multiplier: 0.52
djump-add-velocity-multiplier: 1.8
djump-delay: 1.5

#MESSAGES
sender-instance: "You have to be a player to access §c%s"
no-permission: "§cYou do not have enough permissions to perform this command."
command-format: "§7To use this command, please use the format §c%s§7."
set-lobby-world: "§7You have set the lobby world to §e%s§7."
set-boostpad-block: "§7You have set the boostpad block to §e%s§7."
set-boostpad-plate: "§7You have set the boostpad plate to §e%s§7."
set-boostpad-height: "§7You have set the additional height mult. to §e%s§7."
set-boostpad-velocity: "§7You have set the height mult. to §e%s§7."
broadcast-set-lobby-world: "§7The player §e%s §7has just set the lobby world to §e%s§7."
plugin-info: "§7You are currently running §e%s§7 on version §e%s§7."

#PERMISSIONS
se-admin: "se.admin"
se-doublejump: "se.doublejump"
se-boostpad: "se.boostpad"
se-manage-doublejump: "se.admin.doublejump"
se-manage-boostpad: "se.admin.boostpad"
se-change-lobby-world: "se.admin.changelobbyworld"